### ISSUE TITLE
All the engarde 0.4.0 builds seem to have failed

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/engarde-feedstock#4]
Hey @conda-forge/engarde folks, it looks like the CIs for `engarde 0.4.0` have all failed. Could you please restart them? Also, you might be able to do a re-rendering using `noarch: python`.

**Comment by TomAugspurger** [comment]
Hopefully fixed by #5, if you want to check later today, once the packages are uploaded.

**Comment by pmlandwehr** [comment]
yep, all good!
